name: linux

on:
  push:
    branches:  'master'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          sudo apt-get update && sudo apt-get install -y libxaw7-dev libxrandr-dev libxcb-randr0-dev libx11-dev xserver-xorg-dev xorg-dev libx11-xcb1 libxcb-res0-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libgtk-3-dev
      - name: Build
        run: |
          mkdir ~/build
          linuxBuild/build.sh ~/build
      - name: Compress Artifacts
        run: |
          cd ~/build/avBuilt
          tar -zcvf ~/build.tar.gz *
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: avBuiltLinux.tar.gz
          path: ~/build.tar.gz