name: macOS

on:
  push:
    branches: 'master'

jobs:
  build-x86_64:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir ~/build
          macBuild/build.sh ~/build x86_64
      - name: Compress Artifacts
        run: |
          cd ~/build/avBuilt
          tar -zcvf ~/build.tar.gz *
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: avBuiltMacOS_x86_64.tar.gz
          path: ~/build.tar.gz
  build-arm:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir ~/build
          macBuild/build.sh ~/build arm64
      - name: Compress Artifacts
        run: |
          cd ~/build/avBuilt
          tar -zcvf ~/build.tar.gz *
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: avBuiltMacOS_arm.tar.gz
          path: ~/build.tar.gz