name: macOS

on:
  push:
    branches: 'master'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        buildType: [Debug, Release]
        buildArch: [x86_64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir ~/build
          macBuild/build.sh ~/build ${{ matrix.buildArch }} ${{ matrix.buildType }}
      - name: Compress Artifacts
        run: |
          cd ~/build/avBuilt
          tar -zcvf ~/build.tar.gz *
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: avBuiltMacOS_${{ matrix.buildArch }}_${{ matrix.buildType }}.tar.gz
          path: ~/build.tar.gz
