name: windows

on:
  push:
    branches:  'master'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: windowsBuild\build.bat C:\build